### PR TITLE
Build then persist Edge hits

### PR DESCRIPTION
**Pull request by nporter-adbe**
## Description

Instead of just persisting the Event we now build the Edge hit then persist the entire hit.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nporter-adbe** [comment]
> Merging #168 (a6859f4) into feature/consent (42c7db2) will increase coverage by 0.00%.

🙃

**Review by emdobrin — CHANGES_REQUESTED** [review]
@nporter-adbe thanks for putting this up. I have a few general request for this PR:

1. I think we should continue queuing events and not EdgeHits as this will allow us to support batching in the future (for example if multiple experience events have same store and identityMap, we can send one network request containing all).

2. We should queue the identityMap and current state store with the event so that the data is associated correctly, but we should not store the configuration and assurance information. The last two should be fetched on the fly when the request is being sent to the server, as the events can be processed in another session and config may be invalid at some point for any reason and it can block the entire queue.

Based on the above I am proposing the following changes: create a EdgeDataEntity class that holds the required information to be queued (event, state store, identityMap). At process time, build the Edge hit based on the event type/source and fetch config and request headers. Having a well defined EdgeDataEntity allows us to add new data in the future if needed for queued hits, without requiring a database migration.

**Comment by nporter-adbe** [comment]
@emdobrin, I think the batching comment is a good point, but I have some concerns with the remaining feedback.

1. Config fetching:  The current implementation does not block the queue when the config is invalid. Instead, it just drops events which is consistent with the behavior in other extensions and platforms. If we have the scenario:
 
1.1: App is launched with an invalid config
1.2: Hits are queued with this invalid config
1.3 Config updated to a valid config
1.4 Hits are queued

It doesn't seem correct that we would assume that hits queued in 1.2 would automatically be associated with the new config in 1.3. It seems undesired to associate hits in 1.2 with a configuration that didn't exist when they were queued. Thus they should be dropped since they were queued when the SDK was in an invalid state.

2. Assurance integration ID: I still think that persisting the Assurance integration ID is the correct approach. Imagine the scenario where you queue a hit that is persisted in an app that does not contain Assurance, and that hit doesn't go out before the app is closed. Then you relaunch the app with Assurance included. I wouldn't expect a hit that was queued when Assurance wasn't present to contain an integration ID.

3. Database migration: I don't see how an `EdgeDataEntity` would have any database migration advantages over what is currently the `EdgeHit`. Both would be `Codable` types with well-defined data, and adding/removing properties would require migrating the type from persistence.

**Comment by nporter-adbe** [comment]
Closing this, will open a new PR with your feedback, but still have some concerns as listed above.

**Comment by emdobrin** [comment]
1. The configId might be worth storing in the data entity as  this shouldn't block the queue in any way because it is a query parameter in the request. But we need to think more about any edge-cases here: like config with org id1, state store with orgid 1, edge configid1, config updated with org id2, edge config2. 
Also, if we need to store other config keys in the future, for example server name or the edge endpoint (https://github.com/adobe/aepsdk-edge-ios/issues/84), we have to handle on the fly. These are keys that can be modified with remote configuration, at runtime, so if any hit gets stuck in the queue it requires app update to unblock it.

2. Assurance can be enabled at any point at runtime, and it should catch all the requests from the moment it was started, so I think we need to pull the integration id at processing time. If I reverse your example and I have an assurance session, queued the hits, closed the app, reopen app without assurance session, I am expecting not to see the assurance integration id in these calls. I should only see that when assurance is active at the moment of event processing.

3. I think the confusing part here is the name `EdgeHit`. That class was originally added for encapsulating the fields required for an Edge network request. The `EdgeHit` and the `EdgeDataEntity` have different fields based on how they are used. Here is a sample:
```
EdgeDataElement {
   let event: Event // only one event queued at a time
   let identityMap: [String: Any]
   let stateStore: [String: Any]?

   var newOptionalField: String? // new field in the future, preferable it should be optional so it doesn't break compatibility and it doesn't require db migration
   let newRequiredField: String // requires migration
}
```
```
EdgeHit {
    var configId: String 
    var requestId: String
    func getType() -> ExperienceEdgeRequestType
    func getPayload() -> String?
    func getStreamingSettings() -> Streaming?
}

ExperienceEventsEdgeHit {
   EdgeHit + EdgeRequest (list of events when batching collected from multiple EdgeDataElements)
}
```
That's why I think the db migration shouldn't be impacted by changes in the network request payload `EdgeHit` and subclasses, but it should be impacted by changes in the `EdgeDataEntity`, if it introduces required properties for processing.

**Pull request closed without merging**
